- Reviewed by Colin per ENG-246 as a fix for EG-396 - Removed client from strategyagent's dependencies - Added geronimo-jms_1.1_spec to core's runtime dependencies because spring jms code depends on jms classes. For that reason, the jms classes need to be loaded by the same classloader as the one loading spring classes. If we do not add it to core's dependency and copy it into modules/jars, the spring classes generate a NoClassDefFoundError when they are loaded. - Update source/pom.xml to build photon last. One no longer has to wait for photon to build, to figure out if all the unit tests pass. - Installer changes have already been checked in by Ken